src/ecoCases/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.CreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.UpdateView.as_view(),
        name='update'),  # /tweet/1/update
    url(r'^(?P<pk>\d+)/delete/$', views.DeleteView.as_view(),
        name='delete'),  # /tweet/1/update
    url(r'^(?P<ecocase_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^user/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

src/ecocases/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.EcoCaseListAPIView.as_view(), name='list'),  # api/ecocases
    # url(r'^create/$', views.CreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/update/$', views.UpdateView.as_view(),
    #     name='update'),  # /tweet/1/update
    # url(r'^(?P<pk>\d+)/delete/$', views.DeleteView.as_view(),
    #     name='delete'),  # /tweet/1/update
    # url(r'^(?P<ecocase_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # url(r'^user/(?P<username>\w+)/$', views.profile, name='profile'),
    # url(r'^login/$', views.login_view, name='login'),
    # url(r'^logout/$', views.logout_view, name='logout'),
]

src/plfAliennor/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^ecocases/', include('ecocases.urls', namespace='ecocases')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^api/ecocases/', include('ecocases.api.urls', namespace='ecocases-api')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/ecoCases/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.forms import TextInput, Textarea
from django.core.files.storage import FileSystemStorage
from tinymce import models as tinymce_models
from django.contrib.auth.models import User


ecocase_image_fs = FileSystemStorage(location='/media/ecocases/')
esm_choices = (
    ('esm1', 'ESM1'),
    ('esm2', 'ESM2'),
    ('esm3', 'ESM3'),
    ('esm4', 'ESM4'),
    ('esm5', 'ESM5'),
    ('esm6', 'ESM6'),
    ('esm7', 'ESM7'),
    ('esm8', 'ESM8'),
)

def make_upload_path(instance, filename):
    file_root, file_ext = os.path.splitext(filename)
    dir 

class EcoCase(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    ecocase_title = models.CharField(max_length=200)
    ecocase_description = tinymce_models.HTMLField()
    ecocase_characters = tinymce_models.HTMLField()
    timestamp = models.DateTimeField(null=True)
    ecocase_image_urls = models.CharField(max_length=2000, default='')
    ecocase_images = models.FileField(upload_to='ecocases', null=True)

    def __str__(self):
        return self.ecocase_title

    def ecocase_image_url_list(self):
        return self.ecocase_image_urls.split(';')

    def first_image_url(self):
        return self.ecocase_image_urls.split(';')[0]


class ESM(models.Model):
    ecocase = models.ForeignKey(EcoCase, on_delete=models.CASCADE)
    esm_title = models.CharField(max_length=200)
    esm_type = models.CharField(
        max_length=100, choices=esm_choices, default='ESM01')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.esm_title
    
    def esm_file_url(self):
        return 'ecocases/pdfs/' + str(self.esm_type) + '.pdf'
    

src/ecocases/forms.py
import datetime
from django import forms
from .models import EcoCase
from tinymce.widgets import TinyMCE
from django.contrib.admin import widgets
from django.contrib.auth import authenticate


class EcoCaseForm(forms.ModelForm):
    ecocase_title = forms.CharField(max_length=200)
    ecocase_description = forms.CharField(widget=TinyMCE(
        attrs={'rows': 4, 'cols': 100}), max_length=300)
    ecocase_characters = forms.CharField(
        widget=TinyMCE(attrs={'rows': 100, 'cols': 500}))
    ecocase_images = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = EcoCase
        fields = ('ecocase_title', 'ecocase_description',
                  'ecocase_characters', 'ecocase_images')
    # ecocase_title = forms.CharField(max_length=200)
    # ecocase_description = forms.CharField(widget=forms.Textarea, max_length=300)
    # ecocase_characters = forms.CharField(widget=forms.Textarea, max_length=5000)
    # ecocase_image_urls = forms.CharField(max_length=None)
    # ecocase_images = forms.FileField()
    # pub_date = forms.DateTimeField('date published')


class LoginForm(forms.Form):
    username = forms.CharField(label='User Name', max_length=64)
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError(
                "Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user

src/ecoCases/views.py
import os
import datetime
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.views.generic.edit import FormView
from django.template import loader
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from .models import EcoCase, ESM
from .forms import EcoCaseForm, LoginForm
from .mixins import FormUserNeededMixin, UserOwnerMixin

from pprint import pprint

# esms = [
#     {'esm1': "Innover par la création de valeur en prenant en compte l'ensemble des parties prenantes"},
#     {'esm2': 'Innover par le biomimétisme'},
#     {'esm3': 'Innover par la prise en compte des éco-usages et les utilisateurs finaux'},
#     {'esm4': "Innover par les services et l'économie de fonctionnalité"},
#     {'esm5': 'Innover par de nouveaux modes de financement'},
#     {'esm6': 'Innover par le bouclage de flux (matières, informations…)  et les circuits courts'},
#     {'esm7': 'Innover par les matériaux et production'},
#     {'esm8': "Innover par la gestion du transfert d'impact et l'effet rebond"}
# ]

esms = [
    "Innover par la création de valeur en prenant en compte l'ensemble des parties prenantes",
    'Innover par le biomimétisme',
    'Innover par la prise en compte des éco-usages et les utilisateurs finaux',
    "Innover par les services et l'économie de fonctionnalité",
    'Innover par de nouveaux modes de financement',
    'Innover par le bouclage de flux (matières, informations…)  et les circuits courts',
    'Innover par les matériaux et production',
    "Innover par la gestion du transfert d'impact et l'effet rebond"
]


class IndexView(generic.ListView):
    '''
        Display five lastest ecocases by pub_date.
    '''
    template_name = 'ecocases/index.html'
    context_object_name = 'latest_ecocase_list'

    def get_queryset(self):
        """Return the last five added ecocase. """
        return EcoCase.objects.order_by('-timestamp')[:5]


class DetailView(generic.DetailView):
    '''
        Display ecocase by ecocase_id
    '''
    model = EcoCase
    template_name = 'ecocases/detail.html'


# class CreateView(generic.CreateView):
#     '''
#         Create new ecocase
#     '''
#     model = EcoCase
#     template_name = 'ecocase/post_ecocase.html'
#     form_class = EcoCaseForm

class CreateView(FormUserNeededMixin, FormView):
    form_class = EcoCaseForm
    template_name = 'ecocases/create.html'
    success_url = reverse_lazy('ecocases:index')

    def post(self, request, *args, **kwargs):
        # uploaded_dir = settings.MEDIA_ROOT + 'ecocases/'
        # # uploaded_dir = os.path.join(settings.MEDIA_ROOT, '/ecocases/')
        # print('media_root: '+ settings.MEDIA_ROOT)
        # print('upload_dir:', uploaded_dir)
        # uploaded_file_urls = []

        # form_class = self.get_form_class()
        # form = self.get_form(form_class)
        # uploaded_files = request.FILES.getlist('ecocase_images')

        # if form.is_valid():
        #     joined_title = '_'.join(form.cleaned_data['ecocase_title'].split(' '))
        #     for count, x in enumerate(uploaded_files):
        #         def save_uploaded_file(f, uploaded_file_url):
        #             print('upload_file_url:' + uploaded_file_url)
        #             with open(uploaded_file_url, 'wb+') as destination:
        #                 for chunk in f.chunks():
        #                     destination.write(chunk)
        #         uploaded_file_url = uploaded_dir + joined_title + '_' + str(count) + '.' + x.name.split('.')[-1]
        #         print('upload_file_url2:' + uploaded_file_url)
        #         save_uploaded_file(x, uploaded_file_url)
        #         uploaded_file_urls.append(uploaded_file_url)

        #     print(uploaded_file_urls)

        #     ecocase = EcoCase(ecocase_title=form.cleaned_data['ecocase_title'],
        #                     ecocase_description=form.cleaned_data['ecocase_description'],
        #                     ecocase_characters=form.cleaned_data['ecocase_characters'],
        #                     ecocase_image_urls=';'.join(uploaded_file_urls)
        #                     )
        #     ecocase.save()

        #     return self.form_valid(form)
        # else:
        #     return self.form_invalid(form)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        images = request.FILES.getlist('ecocase_images')
        fs = FileSystemStorage(location=os.path.join(
            settings.BASE_DIR, 'media/ecocases'))
        image_url_list = []
        if form.is_valid():
            joined_title = '_'.join(
                form.cleaned_data['ecocase_title'].split(' '))

            for count, x in enumerate(images):
                image_extension = x.name.split('.')[-1]
                new_image_name = joined_title + '_' + \
                    str(count) + '.' + image_extension
                uploaded_image = fs.save(new_image_name, x)
                image_url_list.append('../media/ecocases/' + new_image_name)

            ecocase = EcoCase(ecocase_title=form.cleaned_data['ecocase_title'],
                              ecocase_description=form.cleaned_data['ecocase_description'],
                              ecocase_characters=form.cleaned_data['ecocase_characters'],
                              ecocase_image_urls=';'.join(image_url_list),
                              timestamp=datetime.datetime.now(),
                              user=request.user,
                              )
            ecocase.save()
            for i in range(1, 9):
                ecocase.esm_set.create(
                    esm_title='Ecocase' + str(ecocase.id) + '_' + esms[i - 1],
                    esm_type='ESM' + str(i),
                    votes=0
                )

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

# def post_ecocase(request):
#     if request.method == 'POST':
#         form = request.POST
#         images = request.FILES.getlist('ecocase_images')
#         f_s = FileSystemStorage()

#         if form.is_valid():
#             joined_title = form.cleaned_data['ecocase_title'].join('_')
#             uploaded_image_urls = []
#             for count, x in enumerate(images):
#                 new_image_name = joined_title + '_' + str(count)
#                 uploaded_image = f_s.save(new_image_name, x)
#                 uploaded_image_urls.append(f_s.url(uploaded_image))
#                 # def process(f):
#                 #     newfilename = joined_title + '_' + str(count)

#                 #     with open('/media/ecocases/images/' + joined_title + '_' + str(count), 'wb+') as destination:
#                 #         for chunk in f.chunks():
#                 #             destination.write(chunk)
#                 # process(x)
#             ecocase = EcoCase(ecocase_title = form.cleaned_data['title'],
#                             ecocase_description = form.cleaned_data['description'],
#                             ecocase_characters = form.cleaned_data['characters'],
#                             ecocase_images = images,
#                             ecocase_image_urls = uploaded_image_urls,
#             )
#             ecocase.save()
#     return render(request, 'ecocases/post_ecocase.html', 'form')

    # def index(request):
    #     '''
    #         Display five lastest ecocases by pub_date.
    #     '''
    #     latest_ecocase_list = EcoCase.objects.order_by('-pub_date')[:5]
    #     context = {'latest_ecocase_list': latest_ecocase_list}
    #     return render(request, 'ecocases/index.html', context)

    # def detail(request, ecocase_id):
    #     '''
    #         Display ecocase by ecocase_id
    #     '''
    #     ecocase = get_object_or_404(EcoCase, pk=ecocase_id)
    #     return render(request, 'ecocases/detail.html', {'ecocase': ecocase})


class UpdateView(UserOwnerMixin, generic.UpdateView):
    queryset = EcoCase.objects.all()
    form_class = EcoCaseForm
    template_name = 'ecocases/update.html'
    success_url = 'ecocases/'


class DeleteView(generic.DeleteView):
    model = EcoCase
    template_name = 'ecocases/confirm_delete.html'
    success_url = reverse_lazy('ecocases:index')


def vote(request, ecocase_id):
    ecocase = get_object_or_404(EcoCase, pk=ecocase_id)
    try:
        selected_esm = ecocase.esm_set.get(pk=request.POST['esm'])
    except (KeyError, ESM.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'ecocases/vote.html', {
            'ecocase': ecocase,
            'error_message': "You didn't select a esm.",
        })
    else:
        selected_esm.votes += 1
        selected_esm.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('ecocases:detail', args=(ecocase.id,)))


def profile(request, username):
    user = User.objects.get(username=username)
    ecocases = EcoCase.objects.filter(user=user)
    return render(request, 'user/profile.html',
                  {'username': username, 'ecocases': ecocases})


# def login_view(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = authenticate(username=username, password=password)
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)

src/ecocases/api/views.py
from rest_framework import generics
from ecocases.models import EcoCase
from .serializers import EcoCaseModelSerializer


class EcoCaseListAPIView(generics.ListCreateAPIView):
    queryset = EcoCase.objects.all()
    serializer_class = EcoCaseModelSerializer

    def get_queryset(self):
        return EcoCase.objects.all()

src/ecoCases/templates/ecocases/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Display ecocase by id -->
<div class="panel-heading">
    <h3>{{ ecocase.ecocase_title }}</h3>
</div>
<!-- <div class="panel-heading">
    <h3 class="panel-title"><a href="{% url 'ecocases:detail' ecocase.id %}">{{ ecocase.ecocase_title }}</a></h3>
</div> -->
<div class="panel-body">
    <div class="row top-buffer">
        <div class="col-md-4">
            <div class="cover-container">
                <ul class="list-inline">
                    {% for image_url in ecocase.ecocase_image_url_list %}
                        <div class="cover-item">
                            <img src="{% static image_url %}" class="center-block" alt="" height="250px">
                        </div>
                    {% endfor %}
                </ul>                
            </div>            
        </div>
        <div class="col-md-8">
            <h4>Description: </h4>
            {% autoescape off %}{{ ecocase.ecocase_description }}{% endautoescape %}
        </div>
    </div>

    <div class="row top-buffer">
        <div class="col-md-12 characters-textarea">
            <h4>Characters  : </h4>
            {% autoescape off %}{{ ecocase.ecocase_characters }}{% endautoescape %}
        </div>
    </div>

    <h4>Associated ESM</h4>        
    {% for esm in ecocase.esm_set.all %}
        <div class="row top-buffer">
            <div class="col-md-8">
                <li>{{ esm.esm_title }}</li>
            </div>
            <div class="col-md-4">
                {{ esm.votes }} vote{{ esm.votes|pluralize }}
            </div>
        </div>
    {% endfor %}
    <div class="text-right">
        <a href="{% url 'ecocases:vote' ecocase.id %}">Vote again?</a>
    </div>
    
    <br>
    <div class="text-right">
        <button type="button" class="btn btn-secondary"><a href="{% url 'ecocases:index' %}">Back to list</a></button>
        <button type="button" class="btn btn-secondary"><a href="{% url 'ecocases:update' ecocase.id %}">Update</a></button>
        <button type="button" class="btn btn-secondary"><a href="{% url 'ecocases:delete' ecocase.id %}">Delete</a></button>
    </div>
</div>  
{% endblock %}

src/ecoCases/templates/ecocases/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block script %}
<script>
$(document).ready(function(){
    console.log("working")
    $.ajax({
        url: "/api/ecocases",    
        method: "GET",
        success: function(data){
            $.each(data, function(key, value){
                console.log(key);
                console.log(value.ecocase_characters);
                $("#ecocase-characters").append(value.ecocase_characters)
            });
       }
    });
});
</script>
{% endblock %}

{% block content %}
<div id="ecocase-characters">

</div>
<!-- Display latest added ecocases -->
    <div class="panel panel-default">
        {% if latest_ecocase_list %}
            {% for ecocase in latest_ecocase_list %}
                {% if ecocase.user.username %}
                <a class="panel panel-username" 
                    href="{% url 'ecocases:profile' ecocase.user.username %}">
                    by {{ ecocase.user.username }}
                </a>
                {% endif %}
                <div class="panel-heading">
                    <h4 class="panel-title"><a href="{% url 'ecocases:detail' ecocase.id %}">{{ ecocase.ecocase_title }}</a></h4>
                </div>
                <div class="panel-body">
                    <div class="row top-buffer">
                        <div class="col-md-4">
                            {% if ecocase.first_image_url %}
                                <div class="ecocase-photo">
                                    <img src="{{ ecocase.first_image_url }}" class="center-block" alt="" width="300px">
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-8">
                            {% autoescape off %}{{ ecocase.ecocase_description }}{% endautoescape %}                             
                        </div>
                    </div>
                </div>   
                <hr>                             
            {% endfor %}
        {% else %}
        <p>No ecocases are available.</p>
        {% endif %} 
    </div>    
    <div class="text-right">
        <button type="button" class="btn btn-default"><a href="{% url 'ecocases:create' %}">Create</a></button>
    </div>
{% endblock %}